# /*
#  * Copyright (c) 2025 IBM Corporation
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applications.ui.name }}
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.applications.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applications.ui.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.applications.ui.name }}      
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      volumes:
      - name: certs
        secret:
          secretName: {{ .Values.secrets.certs.name }}
      - name: artifact-volume
        emptyDir: {}
      initContainers:
      - name: {{ .Values.applications.ui.initContainer.name }}
        image: {{ .Values.applications.ui.initContainer.imageName }}:{{ .Values.applications.ui.initContainer.tagName }}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "cp -rp /artifacts/* /shared"]
        volumeMounts:
          - name: artifact-volume
            mountPath: /shared
      containers:
      - name: {{ .Values.applications.ui.name }}
        image: {{ .Values.applications.ui.imageName }}:{{ .Values.applications.ui.imageTag | default .Chart.AppVersion}}
        volumeMounts:
        - name: certs
          mountPath: {{ .Values.secrets.certs.mountPath }}
          readOnly: true
        - name: artifact-volume
          mountPath: {{ .Values.applications.ui.initContainer.mountPath }}
        envFrom:
        - configMapRef:
            name: {{ .Values.applications.ui.name }}-config
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1724
        resources:
          limits:
            cpu: {{ .Values.applications.ui.resources.limits.cpu }}
            memory: {{ .Values.applications.ui.resources.limits.memory }}
          requests:
            cpu: {{ .Values.applications.ui.resources.requests.cpu }}
            memory: {{ .Values.applications.ui.resources.requests.memory }}
        ports:
          - containerPort: 8443
            name: http
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -fk -s --cert /certs/ui-cert.pem --key /certs/ui-key.pem  https://localhost:8443/controlplane/api/ui/health/readiness || exit 1"
          initialDelaySeconds: 100
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 15
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -fk -s --cert /certs/ui-cert.pem --key /certs/ui-key.pem  https://localhost:8443/controlplane/api/ui/health/liveness || exit 1"
          initialDelaySeconds: 100
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 15
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
          - name: {{ .Values.imagePullSecretName }}
---